---

#
# MacOS
#

- name: MacOS GnuPG 
  block:
    - homebrew:
        name: [
                'gnupg',
                'pinentry',
                'pinentry-mac'
              ]
        state: present
  when: distro.macos


#
# Linux
#

- name: Debian GnuPG
  apt:
    name: gnupg
    state: present
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
  when: distro.debian


#
# XDG Spec
#
- stat:
    path: ~/.gnupg
  register: gnupg_dir

- stat:
    path: "{{xdg.config}}/gnupg"
  register: gnupg_conf_dir

- name: Relocate GnuPG folder
  command: mv ~/.gnupg "{{xdg.config}}/gnupg"
  when: gnupg_dir.stat.exists and not gnupg_conf_dir.stat.exists

- name: Symlink gnupg
  file:
    src: "~/.config/gnupg"
    dest: "{{user_home}}/.gnupg"
    state: link
  tags: [symlink]

- template:
    src: "{{item}}.j2"
    dest: "{{user_home}}/.gnupg/{{item}}"
  with_items:
    - "gpg.conf"
    - "gpg-agent.conf"
