---
#
# 
# osx_image: 10.12 see: https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version

sudo: required
language: objective-c
osx_image: xcode9.2 
branches:
  only:
    - master
env:
  global:
    - INITIO_TEST=true
  matrix:
    - EXTRA_VARS="endpoint=laptop config_for=home proceed_with_secrets=no secrets_repo_uri=null"
 

before_install:
  # Uninstall existing brew installation.
  - 'ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"'
  - rm -rf /usr/local/Homebrew
  - rm -rf /usr/local/Caskroom
  - rm -rf /usr/local/bin/brew


install: ./.local/share/initio/bootstrap.sh

  
script:
  # Install dependencies.
  - "ansible-galaxy install -r .config/initio/requirements.yml"

  # Check the role/playbook's syntax.
  - "ansible-playbook -i .config/initio/tests/hosts .config/initio/runbook.yml --syntax-check"

  # Test the playbook.
  - >
    travis_wait 30 
    ansible-playbook 
      -vv
      --ask-become-pass     
      --extra-vars $EXTRA_VARS
      --connection=local
      -i .config/initio/test/hosts 
      .config/initio/runbook.yml


  # Test the playbook's idempotence.
  - idempotence=$(mktemp)
  - >
    ansible-playbook 
      -vv
      --ask-become-pass     
      --extra-vars $EXTRA_VARS
      --connection=local
      -i .config/initio/test/hosts 
      .config/initio/runbook.yml
    | tee -a ${idempotence}"
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
