---

- include_role:
    name: geerlingguy.homebrew
  when: ansible_distribution in distros.mac

- apt:
    name:  "{{ item }}"
    state: present
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
  with_items:
    - gnupg
  when: ansible_distribution in distros.debian