---

- include_role:
    name: geerlingguy.homebrew
  when: distro.macos

- apt:
    name:  "{{ item }}"
    state: present
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
  with_items:
    - gnupg
  when: distro.debian


- file:
    path: "{{xdg.config}}/gnupg"
    state: directory

- name: Symlink gnupg
  file:
    src: ".config/gnupg"
    dest: "{{user_home}}/.gnupg"
    state: link

- template:
    src: "{{item}}.j2"
    dest: "{{user_home}}/.gnupg/{{item}}"
  with_items:
    - "gpg.conf"
    - "gpg-agent.conf"
