---

#
# MacOS
#

- name: MacOS GnuPG 
  block:
    homebrew:
      name: "{{item}}"
      state: present
    with_items:
      - gnupg
      - pinentry
      - pinentry-mac
  when: distro.macos


#
# Linux
#

- name: Debian GnuPG
  apt:
    name: gnupg
    state: present
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
  when: distro.debian


#
# XDG Spec
#

- file:
    path: "{{xdg.config}}/gnupg"
    state: directory

- name: Symlink gnupg
  file:
    src: ".config/gnupg"
    dest: "{{user_home}}/.gnupg"
    state: link

- template:
    src: "{{item}}.j2"
    dest: "{{user_home}}/.gnupg/{{item}}"
  with_items:
    - "gpg.conf"
    - "gpg-agent.conf"
