---

#
# Common
#
- name: SSH Authorized Keys
  get_url:
    url: "{{initio.ssh.authorized_keys}}"
    dest: ~/.ssh/authorized_keys
    mode: 0600
  ignore_errors: yes

#
# Mac OS
#
- template:
    src: macos/sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0644
  when: distro.macos
  become: true

  