---

- homebrew:
    name: "{{item}}"
    state: present
  with_items:
    - git 
    # - htop # see: https://github.com/Homebrew/homebrew-core/pull/22479
    - mas
    - md5deep
    - python3
    - rmtrash
    - tmux
    - tree
    - vim
    - wakeonlan
    - wget

- name: OSXFuse
  block:
    - name: sudo brew workaround
      command: "echo none"
      become: yes
    - homebrew_cask:
        name: "{{item}}"
        state: present
      with_items:
        - osxfuse

- name: Override system curl
  block:
    - homebrew:
        name: curl
        state: present
        install_options: with-openssl
    - command: brew link --force curl
      tags: [symlink]
  
