---

- homebrew:
    name: "{{item}}"
    state: present
  with_items:
    - gpg-suite
    - dockutil

- homebrew_cask:
    name: "{{item}}"
    state: present
  with_items:
    - disk-inventory-x
    - Firefox
    - google-chrome
    - keka
    - keybase
    - sublime-text
    - veracrypt
    - vlc
