---

- homebrew:
    name: [
      'git', 
      # - htop # see: https://github.com/Homebrew/homebrew-core/pull/22479
      'mas', 
      'mackup', 
      'md5deep', 
      'python3', 
      'rmtrash', 
      'tmux', 
      'tree', 
      'vim', 
      'neovim', 
      'wakeonlan', 
      'wget'
    ]

    state: present

- name: OSXFuse
  block:
    - name: sudo brew workaround
      command: "echo none"
      become: yes
    - homebrew_cask:
        name: ['osxfuse']
        state: present      

- name: Override system curl
  block:
    - homebrew:
        name: curl
        state: present
        install_options: with-openssl
    - command: brew link --force curl
      tags: [symlink]
  
