---

- homebrew:
    name: "{{item}}"
    state: present
  with_items:
    - dockutil

- homebrew_cask:
    name: "{{item}}"
    state: present
  with_items:
    - disk-inventory-x
    - firefox
    - google-chrome
    - keka
    - keybase
    - veracrypt
    - vlc

- command: "echo none"
  become: yes

- homebrew_cask:
    name: "{{item}}"
    state: present
  with_items:
    - gpg-suite
