---

- name: sudo brew workaround
  command: "echo none"
  become: yes

- homebrew:
    name: ['dockutil']
    state: present

- homebrew_cask:
    name: [
            'disk-inventory-x',
            'firefox',
            'google-chrome',
            'keka',
            'keybase',
            'signal',
            'veracrypt',
            'vlc'
          ]
    state: present  
  ignore_errors: yes

- name: GPG Suite
  block:
    - name: sudo brew workaround
      command: "echo none"
      become: yes
    - homebrew_cask:
        name: [
                'gpg-suite'
              ]
        state: present
