---
#
# Repo universe
#
- homebrew_tap:
    name: caskroom/cask
  when: distro.macos


#
# MacOS
#
- block:
  - include_tasks: macos-cli.yml
  - include_tasks: macos-gui.yml
    when: endpoint_type == "desktop"
  when: distro.macos


#
# Linux
#
- block:
  - include_tasks: linux-cli.yml
  - include_tasks: linux-gui.yml
    when: endpoint_type == "desktop"
  when: distro.linux


#
# Role abstractions
#
- name: Role based commons
  block:
    - include_role:
        name: "{{item}}"
      with_items:
        - terminal
        - sublime-text
  when: endpoint_type == "desktop"


#
# Python
#
    
- pip:
    requirements: "files/python3-requirements.txt"
    executable: pip3


