---
#
# Repo universe
#
- homebrew_tap:
    name: homebrew/cask
  when: distro.macos


#
# MacOS
#
- block:
  - include_tasks: macos-cli.yml
  - include_tasks: macos-gui.yml
    when: endpoint_type == "desktop"
  - include_tasks: macos-personal.yml
    tags: [home, personal]  
  when: distro.macos


#
# Linux
#
- block:
  - include_tasks: linux-cli.yml
  - include_tasks: linux-gui.yml
    when: endpoint_type == "desktop"
  when: distro.linux


#
# Python
#
- pip:
    requirements: "{{role_path}}/files/python3-requirements.txt"
    executable: pip3


