---
#
# Repo universe
#
- homebrew_tap:
    name: caskroom/cask
  when: distro.macos


#
# MacOS
#
- block:
  - include_tasks: macos-cli.yml
  - include_tasks: macos-gui.yml
    when: endpoint_type == "desktop"
  when: distro.macos


#
# Linux
#
- block:
  - include_tasks: linux-cli.yml
  - include_tasks: linux-gui.yml
    when: endpoint_type == "desktop"
  when: distro.linux


#
# Role abstractions
#
- include_role: name=dropbox


# - name: Roles based cli commons
#   block:
#     - include_role:
#         name: "{{item}}"
#       with_items:
#         - 
#   when: endpoint_type == "console"


#
# Python
#
- pip:
    requirements: "files/python3-requirements.txt"
    executable: pip3


