---

#
# MacOS
#
- name: Development tools
  block:    
    - homebrew_cask:
        name: [
                'gitkraken',
                'vagrant',
                'vagrant-manager',
                'kitematic'
              ]
        state: present
    - homebrew_cask: 
        name: [
                'wireshark',
                'docker',  
                'postgres',
                'virtualbox' # cant automate without deactiving SIP which needs a reboot
              ]
        state: present        
      ignore_errors: yes  
      tags: [blockblock]
    - homebrew_cask:
        name: [
                'rubymine',
                'pycharm',
                'vmware-fusion',
              ]
        state: present
      tags: [nobuild]
    - command: mas install {{item}}
      with_items:
        - 497799835 # Xcode
      tags: [nobuild, bigdl]
    - include_role: 
        name: packages/terminal
    - include_role: 
        name: packages/sublime-text
    - include_tasks: macos-prefs.yml
  when: distro.macos
  tags: [development]

#
# Common
#
- pip:
    name: git+https://github.com/larsks/ansible-toolbox
    executable: pip3

#
# Python
#
- pip:
    name: "{{item}}"
    executable: pip3
  with_items:
    - virtualenv
    - virtualenvwrapper

#
# Ruby
#
- gem:
    name: tmuxinator
    state: latest
  ignore_errors: yes
  environment:
    GEM_HOME: "{{user_home}}/.local/share/gem"

