---

#
# MacOS
#
- name: Development tools
  block:    
    - homebrew_cask:
        name: "{{item}}"
        state: present
      with_items:
        - gitkraken
        - vagrant
        - vagrant-manager
        - kitematic
    - homebrew_cask: 
        name: "{{item}}"
        state: present
      with_items:
        - wireshark
        - docker  
        - postgres
      tags: [blockblock]
    - homebrew_cask:
        name: "{{item}}"
        state: present
      with_items:
        - rubymine
        - pycharm
        - vmware-fusion
      tags: [nobuild]
    - include_role: name=terminal
    - include_role: name=sublime-text
    - include_tasks: macos-prefs.yml
  when: distro.macos
  tags: [development]

