---

#
# MacOS
#
- name: Development tools
  block:    
    - homebrew_cask:
        name: 'gitkraken'
        state: present
    - homebrew_cask:
        name: 'vagrant'
        state: present
    - homebrew_cask:
        name: 'vagrant-manager'
        state: present
    - homebrew_cask:
        name: 'kitematic'
        state: present
    - homebrew_cask:
        name: 'wireshark'
        state: present
    - homebrew_cask:
        name: 'docker'
        state: present
    - homebrew_cask:
        name: postgres
        state: present

    #
    # Virtualization
    #
    - homebrew_cask: 
        name: 'virtualbox' # cant automate without deactiving SIP which needs a reboot            
        state: present        
      ignore_errors: yes  
      tags: [nobuild, blockblock]
    - homebrew_cask:
        name: 'vmware-fusion',              
        state: present
      tags: [nobuild]

    #
    # IDEs
    #
    - homebrew_cask:
        name: 'intellij-idea'
        state: present  
    # - homebrew_cask:
    #     name: 'rubymine'
    #     state: present
    - homebrew_cask:
        name: 'pycharm'
        state: present
    - name: Xcode
      command: mas install 497799835      
      tags: [nobuild, bigdl]
    
    
    - include_role: 
        name: packages/terminal
    - include_role: 
        name: packages/sublime-text
    - include_tasks: macos-prefs.yml

  when: distro.macos
  tags: [development]

#
# Common
#
- pip:
    name: git+https://github.com/larsks/ansible-toolbox
    executable: pip3

#
# Python
#
- pip:
    name: "{{item}}"
    executable: pip3
  with_items:
    - virtualenv
    - virtualenvwrapper

#
# Ruby
#
- gem:
    name: tmuxinator
    state: latest
  ignore_errors: yes
  environment:
    GEM_HOME: "{{user_home}}/.local/share/gem"

