---

#
# MacOS
#
- name: Sublime text
  block:
    - homebrew_cask:
        name: sublime-text
        state: present
    - get_url:
        url: "{{sublime_text.package_control_uri}}"
        dest: "~Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package"
    - name: Remove default directory
      file:
        path: "~Library/Application Support/Sublime Text 3/Packages/User"
        state: absent
    - name: Symlink sublime user configs
      file:
        src: "{{xdg.config}}/sublime-text-3/Packages/User"
        dest: "~Library/Application Support/Sublime Text 3/Packages/User"
        state: link
  when: distro.macos


#
# Linux
#
- name: Sublime text
  block:
    - apt_repository:
        repo: 'ppa:webupd8team/sublime-text-3'
    - apt:
        name: sublime-text-installer
        state: present
        update_cache: yes
    - name: Install package control      
      file:
        path: "{{xdg.config}}/sublime-text-3/Installed Packages"
        recurse: yes
        state: directory
    - get_url:
        url: "{{sublime_text.package_control_uri}}"
        dest: "{{xdg.config}}/sublime-text-3/Installed Packages/Package Control.sublime-package"
  when: distro.debian

