---

#
# Hardware config
#
- name: Power management settings
  command: pmset -a {{item.key}} {{item.value}}
  with_dict: "{{power_settings.macos}}"
  become: true



#
# Apps
#

- command: mas account
  register: app_store_sigin
  ignore_errors: yes

- pause:
    prompt: | 
      Signin to the Apple App Store, then hit return to continue.
      Notice: that mas will stall if the applications have not been installed
      using the apple store signin provided. Apps need to have been installed 
      at least once to be pickedup by mas.
  when: not (app_store_sigin.stdout is match("@"))
  tags: [nobuild, prompt]

- include_tasks: macos-personal.yml
  tags: [home, personal]

- include_tasks: macos-office.yml



#
# Preferences and Configs
#
- name: MacOS Prefs
  include_role: name=macos-prefs