---
- hosts: laptop
  strategy: linear
  vars:
    endpoint: laptop
    endpoint_type: desktop # desktop as in GUI OS
  vars_files:
    - default.config.yml

  pre_tasks:
    - name: "Preflight checks"
      include_tasks: preflight.yml

  roles:
    - common
    - zsh
    - gnupg
    - dotfiles
    - secrets
    - mackup
    - fonts
    - security
    - laptop

   