---

- include_vars: "{{ item }}"
  with_fileglob:
    - ../config.yml

- meta: end_play
  when: endpoint not in endpoints

- set_fact:
    endpoint_type: "desktop"
  when: endpoint == "laptop" or endpoint == "workstation"

- set_fact:
    endpoint_type: "console"
  when: endpoint_type is not defined

- set_fact:
    distro:
      macos: true
      linux: false
      debian: false
  when: ansible_distribution in distros.mac

- set_fact:
    distro:
      macos: false
      linux: true
      debian: true
  when: ansible_distribution in distros.debian
  