---

#
# Configuration type
# ------------------ 
# home - will provision all configs, and use personal repos
# work - will only provision common configs, and use pub repos
#
config_for: home

#
# Initio configs
# -----------
initio:
  repo: "https://github.com/jnand/initio.git"

  # location of bootstrap cache files
  tmp: "/tmp/initio"

  # playbook alias
  playbooks: "{{playbook_dir}}/playbooks"

  yadm:
    repo: "https://github.com/jnand/yadm.git"

  zim:
    repo: "https://github.com/jnand/zim.git"

  gpg:
    # fingerprint of default key
    default_key: B83550D23D8D862E335EA5A0A63BEFAD44DC80CC

  ssh:
    # deploy key for cloning "secrets" repo
    secrets_key: "path/to/ssh/private/key"

#
# Supported Distro
# ----------------
distros:
  mac:
    - Darwin
    - MacOSX
  debian:
    - Ubuntu
