---

#
# CLI passed configs
# -------------------
# these are better passed via the ansible cli args
#
# computername: ''


#
# Configuration tags
# ------------------ 
# home     - personal configs, secrets, and private repos
# personal
#
# example: $ ansible-playbook --skip-tags "home"


#
# Initio configs
# -----------
initio:
  repo: "https://github.com/jnand/initio.git"

  # location of bootstrap cache files
  tmp: "/tmp/initio"
  bin: "~/.local/lib/inito"

  # playbook alias
  playbooks: "{{playbook_dir}}/playbooks"

  yadm:
    repo: "https://github.com/jnand/yadm.git"

  zim:
    repo: "https://github.com/jnand/zim.git"

  gpg:
    # fingerprint of default key
    default_key: B83550D23D8D862E335EA5A0A63BEFAD44DC80CC

  ssh:
    # deploy key for cloning "secrets" repo

  keepass:
    db_path: "path/to/keepass.kdbx"
    database: "name_of_db.kdbx"
    

#
# Supported Distro
# ----------------
distros:
  mac:
    - Darwin
    - MacOSX
  debian:
    - Ubuntu
