---
#
# Provision components of infrastructure
#
- hosts: all
  strategy: linear
  vars:
    endpoints:
      - laptop
      - workstation
      - headnode
      - fileserver
      - compute
  vars_files:
    - config.yml

#
# Prompt for endpoint and config
#
# TODO: https://github.com/ansible/ansible/issues/32723
  vars_prompt:
    - name: "endpoint"
      prompt: |

        Endpoint type?
        ---------------
        laptop
        workstation
        headnode
        fileserver
        compute

      default: "laptop"
      private: no

  pre_tasks:
    - meta: end_play
      when: endpoint not in endpoints
    - name: "Preflight checks"
      include_tasks: preflight.yml


#
# Common provisioning
#
  roles:
    - common
    - zsh
    - gnupg
    - dotfiles
    - secrets
    - fonts


#
# Endpoint specifics
#
  tasks:
    - include_role:
        name: "{{endpoint}}"
      when: endpoint is defined

