---
#
# Provision components of infrastructure
#
- hosts: all
  strategy: debug
  vars:
    endpoints:
      - laptop
      - workstation
      - headnode
      - fileserver
      - compute
    config_fors:
      - home
      - work
  vars_files:
    - config.yml

#
# Prompt for endpoint and config
#
# TODO: https://github.com/ansible/ansible/issues/32723
  vars_prompt:
    - name: "endpoint"
      prompt: |
        Endpoint type?
        ---------------
        laptop
        workstation
        headnode
        fileserver
        compute
      private: no
    - name: "config_for"
      prompt: |
        Configure for:
        ---------------
        * current: {{config_for}}
        home
        work
      private: no

  tasks:
    # Sanity check vars_propmts
    - meta: end_play
      when: endpoint not in endpoints
    - meta: end_play
      when: config_for not in config_fors



#
# Common provisioning
#
  roles:
    - xdg-base-dir-spec
    - zsh
    - dotfiles


#
# Endpoint specifics
#
    # - name: Load endpoint playbook
      # include: "{{playbook_dir}}/playbooks/{{endpoint}}.yml"
      # when: endpoint is defined
