---
#
# Provision components of infrastructure
#
- hosts: all
  strategy: linear
  vars:
    endpoints:
      - laptop
      - workstation
      - headnode
      - fileserver
      - compute
    config_fors:
      - home
      - work
  vars_files:
    - config.yml

#
# Prompt for endpoint and config
#
# TODO: https://github.com/ansible/ansible/issues/32723
  vars_prompt:
    - name: "endpoint"
      prompt: |

        Endpoint type?
        ---------------
        laptop
        workstation
        headnode
        fileserver
        compute

      default: "laptop"
      private: no
    - name: "config_for"
      prompt: |

        Configure for:
        ---------------
        home
        work

      default: "home"
      private: no

  pre_tasks:
    - meta: end_play
      when: endpoint not in endpoints
    - meta: end_play
      when: config_for not in config_fors

#
# Common provisioning
#
  roles:
    - xdg-base-dir-spec
    - zsh
    - dotfiles


#
# Endpoint specifics
#
  tasks:
    - include: "{{initio.playbooks}}/{{endpoint}}.yml"
      when: endpoint is defined
