---

- name: Power management settings
  command: pmset -a {{item.key}} {{item.value}}
  with_dict: "{{power_settings.macos}}"
  become: true

- name: MacOS Prefs
  include_role:
    name: "macos-prefs"

- name: Wipe all (default) app icons from the Dock
  osx_defaults:
    domain: com.apple.dock
    key: persistent-apps
    type: array

# see: https://github.com/kcrawford/dockutil
- name: Setup Dock
  command: dockutil --add '/Applications/{{item}}.app'
  with_items:
    - Launchpad
    - Safari
    - Firefox
    - Chrome
    - iCal
    # - Todoist
    - Reminders
    - iTerm

# Uses macbuilds launcpad helper script
# see: https://github.com/fgimian/macbuild/blob/master/extras/launchpad.py
# example: ./extras/launchpad.py build host_vars/localhost/launchpad.yaml
- name: Organize launchpad
  shell: ~/.local/lib/initio/launchpad.py build ~/.config/initio/roles/laptop/files/launchpad.yml
  tags: [home, personal]

#
# Apps
#
- name: Todoist
  block:
    - command: mas install 585829637
    - command: dockutil --add /Applications/Todoist.app --after 'iCal'
  tags: [home, personal]

- command: mas install
  with_items:
    - 1160374471 # PiPifier
  tags: [home, personal]

- homebrew_cask:
    name: "{{item}}"
    state: present
  with_items:
    - transmission
    - ubiquiti-unifi-controller
    - backblaze
    - hermes
    - plex-media-player
    - musicbrainz-picard
    - marshallofsound-google-play-music-player
  tags: [home, personal]

- homebrew_cask:
    name: "{{item}}"
    state: present
  with_items:
    - bettertouchtool
    - typora
    - microsoft-office
    - rstudio
    - toggl

- name: Development tools
  homebrew_cask:
    name: "{{item}}"
    state: present
  with_items:
    - gitkraken
    - vagrant
    - vagrant-manager
    - wireshark
    - docker
    - kitematic
    - postgres
    - rubymine
    - pycharm
    - vmware-fusion
  tags: [development]

- name: Samsung SSD Encryption
  block:
    - get_url:
        url: http://downloadcenter.samsung.com/content/SW/201710/20171030152312901/T3_Security_Enabler_for_Mac.pkg
        dest: ~/Downloads/samsung-t3-installer.pkg
    - command: installer -pkg ~/Downloads/samsung-t3-installer.pkg -target /
      become: true

# see: https://github.com/OJFord/loginitems
# example: $ loginitems-add name path hide
- name: Set login items
  shell: >
    {{initio.bin}}/loginitems-add {{item.name}} /Applications/{{item.name}} {{item.value}}
  with_dict:
    Dropbox: false
    iTerm: false
    BetterTouchTool: false
    Qbserve: false



