---

#
# MacOS
#
- block:
    - include_tasks: macos.yml
  when: distro.macos


#
# Linux
#
- block:
    - include_tasks: debian.yml
  when: distro.debian

  
#
# Tooling
#
- include_role: name=terminal
- include_role: name=sublime-text
- include_role: name=development
  tags: [development]