---
- name: Create XDG config
  file:
    path: "{{xdg.config}}"
    state: directory

- name: Create XDG cache
  file:
    path: "{{xdg.cache}}"

- name: Create XDG locals
  file: 
    path: "{{xdg.local}}" 
    state: directory

- file: 
    path: "{{xdg.local}}/{{item}}"
    state: directory
  with_items:
    - lib
    - bin
    - share
    - "share/initio"
