---

- name: Git configs
  file:
    src: ".config/git/gitconfig"
    dest: "{{user_home}}/.gitconfig"
    state: link

- name: SSH configs
  file:
    src: "~/.config/ssh"
    dest: "{{user_home}}/.ssh"
    state: link