---

#
# MacOS
#
- block:
    - homebrew:
        name: "{{item}}"
        state: present
      with_items:
        - zsh
        - zsh-completions
  when: distro.macos


#
# Linux
#
- apt:
    name: zsh
    state: present
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
  when: distro.debian


#
# Update user conf
#
- command: which zsh
  register: zsh_path

- command: whoami
  register: current_user

- name: Update default shell  
  user:
    name: "{{current_user.stdout}}"
    shell: "{{zsh_path.stdout}}"
  become: true
