---
- pause:
    prompt: |
      Proceed with adding secrets? [No]|Yes
  register: proceed_with_secrets
  tags: [prompt]

- include_tasks: tasks.yml
  when: proceed_with_secrets is defined and (proceed_with_secrets.user_input | match("^[Yy](es)?$"))
