---
#
# Secrets repo config
#
- name: Secrets repo config
  block:
  - name: Check for secret config
    stat:
      path: ~/.local/share/initio/secrets.repo
    register: secrets_config

  - pause:
      prompt: "URI for secrets repo"
    register: secrets_repo_uri
    when: not secrets_config.stat.exists

  - name: Save secrets repo URI
    copy:
      content: "{{secrets_repo_uri.user_input}}"
      dest: ~/.local/share/initio/secrets.repo
    when: not secrets_config.stat.exists
  - set_fact:
      secrets_repo: "{{secrets_repo_uri.user_input}}"
    when: not secrets_config.stat.exists

  - name: Read secrets repo config
    slurp:
      src: ~/.local/share/initio/secrets.repo
    register: secrets_repo_uri
    when: secrets_config.stat.exists
  - set_fact:
      secrets_repo: "{{secrets_repo_uri.content | b64decode}}"
    when: secrets_config.stat.exists


#
# Setup secrets repo
#
- name: Check if repo exisits
  stat:
    path: ~/Secrets/.git/config
  register: secrets_git_config

- name: "Cloning secrets"
  shell: >
    GIT_SSH_COMMAND="ssh -i {{initio.ssh.secrets_key}}" 
    git clone {{secrets_repo}} {{secrets.dir}}
  when: not secrets_git_config.stat.exists

- name: Symlink YADM's enc container
  file:
    src: "~/Secrets/Yadm/files.gpg"
    dest: "{{yadm.dir}}/files.gpg"
    state: link

- name: Decrypt YADM's secrets
  shell: |
    source {{user_home}}/.zshrc
    {{yadm.bin}} decrypt
  args:
     executable: "{{zsh_path.stdout}}"
  ignore_errors: yes

- name: Symlink Keepass database
  block:
    - stat:
        path: "{{initio.keepass.db_path}}/{{initio.keepass.database}}"
      register: dropbox_keepass_db
    - file:
        src: "{{initio.keepass.db_path}}/{{initio.keepass.database}}"
        dest: "~/Secure/{{initio.keepass.database}}"
        state: link
      when: dropbox_keepass_db.stat.exists
      