---
#
# Secrets repo config
#  
- name: Check for secret config
  stat:
    path: ~/.local/share/initio/secrets.repo
  register: secrets_config

- block:
  - pause:
      prompt: "URI for secrets repo"
    register: secrets_repo_uri
    when: not secrets_config.stat.exists

  - name: Save secrets repo URI
    copy:
      content: "{{secrets_repo_uri.user_input}}"
      dest: ~/.local/share/initio/secrets.repo
    when: not secrets_config.stat.exists

  - set_fact:
      secrets_repo: "{{secrets_repo_uri.user_input}}"
    when: not secrets_config.stat.exists

  - name: Read secrets repo config
    slurp:
      src: ~/.local/share/initio/secrets.repo
    register: secrets_repo_uri
    when: secrets_config.stat.exists

  - set_fact:
      secrets_repo: "{{secrets_repo_uri.content | b64decode}}"
    when: secrets_config.stat.exists

  when: secrets_repo is not defined


#
# Setup secrets repo
#
- name: Check if repo exisits
  stat:
    path: ~/Secrets/.git/config
  register: secrets_git_config

- name: "Cloning secrets"
  shell: >
    GIT_SSH_COMMAND="ssh -i {{ssh_secrets_key | default(initio.ssh.secrets_key)}}" 
    git clone -b {{computername}} {{secrets_repo}} {{secrets.dir}}
  when: not secrets_git_config.stat.exists

- name: Symlink YADM's enc container
  file:
    src: "~/Secrets/Yadm/files.gpg"
    dest: "{{yadm.dir}}/files.gpg"
    state: link
  tags: [symlink]

- name: Decrypt YADM's secrets
  shell: |
    source {{user_home}}/.zshrc
    {{yadm.bin}} decrypt
  args:
     executable: "{{zsh_path.stdout}}"
  ignore_errors: yes
  tags: [prompt]

- name: Symlink Keepass database
  block:
    - stat:
        path: "{{keepass_db_path | default(initio.keepass.db_path)}}/{{keepass_database | default(initio.keepass.database)}}"
      register: dropbox_keepass_db
    - file:
        src: "{{keepass_db_path | default(initio.keepass.db_path)}}/{{keepass_database | default(initio.keepass.database)}}"
        dest: "~/Secure/{{keepass_database | default(initio.keepass.database)}}"
        state: link
      when: dropbox_keepass_db.stat.exists
  tags: [symlink]
