---
#
# Yubikey setup
# -------------
# see: https://www.yubico.com/support/knowledge-base/categories/articles/yubikey-mac-os-x-login-guide/


- name: Disable FileVault auto login
  shell: >
    defaults write /Library/Preferences/com.apple.loginwindow DisableFDEAutoLogin -bool YES
  become: true

- homebrew_tap:
    name: homebrew/cask-drivers

- homebrew:
    name: "{{item}}"
    state: present
  with_items:
    - ykman
    - ykpers
    - libyubikey
    - pinentry-mac
    - pam_yubico
    - yubico-piv-tool    
    - yubikey-personalization

- homebrew_cask:
    name: "{{item}}"
    state: present
  with_items:
    - yubico-authenticator
    - yubico-yubikey-manager
    - yubico-yubikey-piv-manager
    - yubico-yubikey-personalization-gui

#
# Load saved Yubico secrets
#
- stat:
    path: ~/Secrets/yubico
  register: yubico_secret_dir

- name: Symlink Yubikey secret
  file:
    src: ~/Secrets/yubico
    dest: ~/.ybico
    state: link
  when: yubico_secret_dir.stat.exists
  tags: [symlink]

- file:
    path: ~/.yubico
    mode: 0700
    state: directory
  when: not yubico_secret_dir.stat.exists


#
# Create new yubikey challenge
#
- pause:
    prompt: Create new challenge? [No]|Yes
  register: new_yubikey_challenge
  tags: [nobuild, prompt]

- block:
    - name: Save challenge
      command: ykpamcfg -2
    - name: Verify new challenge
      stat:
        path: "{{item}}"
      with_fileglob:
        - "~/.yubico/challenge-*"
  when: new_yubikey_challenge is defined and (new_yubikey_challenge.user_input | match("^[Yy](es)?$"))
  tags: [nobuild]


#
# Activate PAM module
#
- name: Verify library
  stat:
    path: /usr/local/lib/security/pam_yubico.so
- template:
    src: macos/{{item}}.j2
    dest: "/etc/pam.d/{{item}}"
    mode: 0644
  with_items:
    - screensaver
    - authorization   
  become: true
  tags: [pamlockout]
  