---
#
# Finder
#

- name: Allow quitting via ⌘ + Q; doing so will also hide desktop icons
  osx_defaults:
    domain: com.apple.finder
    key: QuitMenuItem
    type: bool
    value: true

- name: Finder - show status bar
  osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true

- name: Finder - show path bar
  osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true 

- name: When performing a search, search the current folder by default
  osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: "SCcf"

- name: Expand File Info panes General, Open with, and Sharing & Permissions
  shell: >
    defaults write com.apple.finder FXInfoPanesExpanded -dict 
      General -bool true 
      OpenWith -bool true
      Privileges -bool true
  become: true

- name: Finder - show all filename extensions
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true

- name: Disable the warning when changing a file extension
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false

- name: Show icons for hard drives, servers, and removable media on the desktop
  osx_defaults:
    domain: com.apple.finder
    key: "{{item}}"
    type: bool
    value: true
  with_items:
    - ShowExternalHardDrivesOnDesktop
    - ShowHardDrivesOnDesktop
    - ShowMountedServersOnDesktop
    - ShowRemovableMediaOnDesktop

- name: Show hidden files by default
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true

- name: Use list view in all Finder windows by default
  osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: "clmv"

- name: Avoid creating .DS_Store files on network volumes
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true

- name: Display full POSIX path as Finder window title
  osx_defaults:
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: true

