---
#
# System
#

- name: Use a dark menu bar / dock
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleInterfaceStyle
    type: string
    value: "Dark"
    state: present

- name: Show the ~/Library folder
  command: chflags nohidden ~/Library

- name: Show the /Volumes folder
  command: chflags nohidden /Volumes
  become: true

- name: Restart automatically if the computer freezes
  command: systemsetup -setrestartfreeze on
  become: true

- osx_defaults:
    domain: com.apple.universalaccess
    key: reduceTransparency
    type: bool
    value: true
    state: present

- osx_defaults:
    domain: com.apple.systemuiserver
    key: dontAutoLoad
    type: array
    value: 
      - "/System/Library/CoreServices/Menu Extras/TimeMachine.menu"
      - "/System/Library/CoreServices/Menu Extras/User.menu"

- osx_defaults:
    domain: com.apple.systemuiserver
    key: menuExtras
    type: array
    value: 
      - "/System/Library/CoreServices/Menu Extras/Clock.menu"
      - "/System/Library/CoreServices/Menu Extras/AirPort.menu"
      - "/System/Library/CoreServices/Menu Extras/Volume.menu"
      - "/System/Library/CoreServices/Menu Extras/Bluetooth.menu"
      - "/System/Library/CoreServices/Menu Extras/Battery.menu"

- name: Disable smart chars
  osx_defaults:
    domain: NSGlobalDomain
    key: "{{item}}"
    type: bool
    value: false
  with_items:
    - NSAutomaticQuoteSubstitutionEnabled
    - NSAutomaticDashSubstitutionEnabled

- name: Expand save panel by default
  osx_defaults:
    domain: NSGlobalDomain
    key: "{{item}}"
    type: bool
    value: true
  with_items:
    - NSNavPanelExpandedStateForSaveMode
    - NSNavPanelExpandedStateForSaveMode2

- name: Expand print panel by default
  osx_defaults:
    domain: NSGlobalDomain
    key: "{{item}}"
    type: bool
    value: true
  with_items:
    - PMPrintingExpandedStateForPrint
    - PMPrintingExpandedStateForPrint2

- name: Disable Resume system-wide
  osx_defaults:
    domain: com.apple.systempreferences
    key: NSQuitAlwaysKeepsWindows
    type: bool
    value: false

- name: Disable the 'Are you sure you want to open this application?' dialog
  osx_defaults:
    domain: com.apple.LaunchServices
    key: LSQuarantine
    type: bool
    value: false

- name: Enable the debug menu in Disk Utility
  block:
  - osx_defaults:
      domain: com.apple.DiskUtility
      key: DUDebugMenuEnabled
      type: bool
      value: true
  - osx_defaults:
      domain: com.apple.DiskUtility
      key: advanced-image-options
      type: bool
      value: true

- name: Prevent Time Machine from prompting to use new hard drives as backup volume
  osx_defaults:
    domain: com.apple.TimeMachine
    key: DoNotOfferNewDisksForBackup
    type: bool
    value: true

- name: Automatically quit printer app once the print jobs complete
  osx_defaults:
    domain: com.apple.print.PrintingPrefs
    key: "Quit When Finished"
    type: bool
    value: true

- name: Save to disk (not to iCloud) by default
  osx_defaults:
    domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false

- name: Scrollbars
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowScrollBars
    type: string
    value: "Automatic" 
